"""
query/tools.py — parameterised read-only query functions.

Rules:
  40. No SQL is ever generated by a model. These are the ONLY queries.
  41. Every parameter is validated and clamped before use.
  46. All reads from the last passing cycle only.

The @tool decorator registers each function in TOOLS with its name,
description, and parameter spec. The description is what the router
model sees — it must be unambiguous about when the tool applies.
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any, Callable

import edgedash.storage as storage
from edgedash.config import Config
from edgedash.skills import canonical

# ---------------------------------------------------------------------------
# Tool registry and decorator
# ---------------------------------------------------------------------------

TOOLS: dict[str, dict[str, Any]] = {}


def tool(
    description: str,
    params: dict[str, Any],
) -> Callable:
    """
    Register a query function in TOOLS.

    description — what the router model sees. Must be specific enough that
                  the router cannot confuse this tool with another.
    params      — JSON-schema-style spec: {param_name: {type, description, default}}.
                  Used by the router to know what arguments to supply.
    """
    def decorator(fn: Callable) -> Callable:
        TOOLS[fn.__name__] = {
            "fn":          fn,
            "description": description,
            "params":      params,
        }
        return fn
    return decorator


# ---------------------------------------------------------------------------
# Parameter validation helpers
# ---------------------------------------------------------------------------

def _clamp_int(value: Any, lo: int, hi: int, default: int) -> int:
    """Parse and clamp an integer parameter. Returns default on bad input."""
    try:
        v = int(value)
    except (TypeError, ValueError):
        return default
    return max(lo, min(hi, v))


def _safe_skill(value: Any, aliases: dict[str, str]) -> str:
    """Canonicalise and strip a skill string from untrusted model input."""
    if not isinstance(value, str):
        return ""
    return canonical(value, aliases)


def _db(config: Config) -> str:
    return config.db_path


# ---------------------------------------------------------------------------
# Tool 1: companies_hiring
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns the companies that have posted job listings in the last N days, "
        "with their listing count and best fit score. Use when the question is about "
        "which companies are actively hiring or how many listings a company has. "
        "Do NOT use for questions about specific jobs, skills, or score rankings."
    ),
    params={
        "days": {
            "type": "integer",
            "description": "Number of days to look back. Clamped to 1–90.",
            "default": 7,
        }
    },
)
def companies_hiring(config: Config, days: int = 7) -> dict[str, Any]:
    days = _clamp_int(days, 1, 90, 7)
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

    # Read all scored listings through storage (rule 2), filter in Python
    all_listings = storage.get_listings(_db(config), limit=1000, min_score=0)
    recent = [
        r for r in all_listings
        if (r.get("fetched_at") or "") >= cutoff
    ]

    # Aggregate by company
    companies: dict[str, dict[str, Any]] = {}
    for r in recent:
        co = r.get("company") or "Unknown"
        if co not in companies:
            companies[co] = {"company": co, "listing_count": 0, "best_score": 0}
        companies[co]["listing_count"] += 1
        companies[co]["best_score"] = max(
            companies[co]["best_score"], r.get("fit_score") or 0
        )

    rows = sorted(companies.values(), key=lambda x: -x["listing_count"])
    summary = f"{len(recent)} scored listings from the last {days} day(s), {len(rows)} companies."
    return {"rows": rows, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 2: best_matches
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns the highest-scoring job listings with their score, title, company, "
        "location, and fit reason. Use when the question is about the best or "
        "highest-scored jobs, or which jobs to apply to. "
        "Do NOT use for company counts, skill gaps, or trend questions."
    ),
    params={
        "n": {
            "type": "integer",
            "description": "Number of top listings to return. Clamped to 1–25.",
            "default": 10,
        }
    },
)
def best_matches(config: Config, n: int = 10) -> dict[str, Any]:
    n = _clamp_int(n, 1, 25, 10)
    rows = storage.get_listings(_db(config), limit=n, min_score=0)
    # get_listings already returns newest-first; re-sort by score descending
    rows = sorted(rows, key=lambda r: -(r.get("fit_score") or 0))[:n]
    result = [
        {
            "score":   r.get("fit_score"),
            "title":   r.get("title"),
            "company": r.get("company"),
            "location":r.get("location"),
            "reason":  r.get("fit_reason"),
            "url":     r.get("url"),
        }
        for r in rows
    ]
    summary = f"Top {len(result)} scored listing(s) out of all scored listings."
    return {"rows": result, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 3: top_gaps
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns the top skill gaps ranked by opportunity cost — the skills I am "
        "missing that appear most often in high-scoring listings. Use when the question "
        "is about which skills to learn, what is blocking opportunities, or skill gaps. "
        "Do NOT use for listing details, company counts, or trend questions."
    ),
    params={
        "n": {
            "type": "integer",
            "description": "Number of top gaps to return. Clamped to 1–25.",
            "default": 5,
        }
    },
)
def top_gaps(config: Config, n: int = 5) -> dict[str, Any]:
    n = _clamp_int(n, 1, 25, 5)
    all_gaps = storage.get_latest_gap_snapshot(_db(config))
    rows = [
        {
            "rank":             i + 1,
            "skill":            g.get("skill"),
            "listings_blocked": g.get("listings_blocked"),
            "opportunity_cost": round(g.get("opportunity_cost", 0), 2),
            "mean_score":       round(g.get("mean_score", 0), 1),
            "low_confidence":   g.get("low_confidence", False),
        }
        for i, g in enumerate(all_gaps[:n])
    ]
    summary = (
        f"Top {len(rows)} skill gap(s) from a snapshot of {len(all_gaps)} total gaps."
    )
    return {"rows": rows, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 4: gap_detail  (rule 26 drill-down)
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns the specific listings blocked by one named skill gap — title, company, "
        "score, and location. Use when the question asks WHY a skill is a gap, which "
        "specific jobs require it, or asks to drill into one gap. "
        "Requires a skill name. Do NOT use for ranking all gaps or general gap summaries."
    ),
    params={
        "skill": {
            "type": "string",
            "description": "The skill name to drill into (e.g. 'kubernetes', 'spark').",
            "default": "",
        }
    },
)
def gap_detail(config: Config, skill: str = "") -> dict[str, Any]:
    canon_skill = _safe_skill(skill, config.skill_aliases)
    if not canon_skill:
        return {"rows": [], "summary": "No skill specified."}

    # Find the gap entry to get example_ids
    all_gaps = storage.get_latest_gap_snapshot(_db(config))
    gap_entry = next(
        (g for g in all_gaps if g.get("skill") == canon_skill), None
    )

    if gap_entry is None:
        # Also try case-insensitive partial match
        gap_entry = next(
            (g for g in all_gaps if canon_skill in (g.get("skill") or "")), None
        )

    if gap_entry is None:
        return {
            "rows":    [],
            "summary": f"Skill '{canon_skill}' not found in gap snapshot. "
                       f"Available: {', '.join(g['skill'] for g in all_gaps[:10])}",
        }

    example_ids: list[str] = gap_entry.get("example_ids") or []

    # Fetch the actual listings for those IDs
    all_scored = storage.get_listings(_db(config), limit=500, min_score=0)
    id_set = set(example_ids)
    matched = [r for r in all_scored if r.get("id") in id_set]
    matched.sort(key=lambda r: -(r.get("fit_score") or 0))

    rows = [
        {
            "listing_id": r.get("id"),
            "title":      r.get("title"),
            "company":    r.get("company"),
            "score":      r.get("fit_score"),
            "location":   r.get("location"),
            "url":        r.get("url"),
        }
        for r in matched
    ]

    summary = (
        f"Skill '{canon_skill}' blocks {gap_entry['listings_blocked']} listing(s), "
        f"opportunity cost {gap_entry['opportunity_cost']:.2f}. "
        f"Showing {len(rows)} example(s)."
    )
    return {"rows": rows, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 5: trend
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns how the opportunity cost of each skill gap has changed over the last "
        "N weeks, comparing the earliest and latest snapshots in that window. "
        "Use when the question is about change over time, whether gaps are growing or "
        "shrinking, or trend. Do NOT use for current gaps or listing details."
    ),
    params={
        "weeks": {
            "type": "integer",
            "description": "Number of weeks to look back. Clamped to 1–12.",
            "default": 3,
        }
    },
)
def trend(config: Config, weeks: int = 3) -> dict[str, Any]:
    weeks = _clamp_int(weeks, 1, 12, 3)

    n_snapshots = storage.get_snapshot_count(_db(config))
    if n_snapshots < 2:
        return {
            "rows":    [],
            "summary": f"Only {n_snapshots} snapshot(s) available. "
                       f"Trend requires at least 2. Run more cycles.",
        }

    _, e_at, early_rows = storage.get_gap_snapshot_by_position(_db(config), "earliest")
    _, l_at, late_rows  = storage.get_gap_snapshot_by_position(_db(config), "latest")

    early_map = {r["skill"]: r["opportunity_cost"] for r in early_rows}
    late_top10 = late_rows[:10]

    rows = []
    for g in late_top10:
        skill       = g["skill"]
        latest_cost = g["opportunity_cost"]
        early_cost  = early_map.get(skill)
        change      = (latest_cost - early_cost) if early_cost is not None else None
        pct         = (change / early_cost * 100) if (change is not None and early_cost) else None
        rows.append({
            "skill":        skill,
            "earliest":     round(early_cost, 2) if early_cost is not None else None,
            "latest":       round(latest_cost, 2),
            "change":       round(change, 2) if change is not None else None,
            "change_pct":   round(pct, 1) if pct is not None else None,
            "is_new":       early_cost is None,
        })

    e_ts = e_at[:19].replace("T", " ")
    l_ts = l_at[:19].replace("T", " ")
    summary = (
        f"Trend for top 10 gaps. "
        f"Comparing earliest snapshot ({e_ts}) to latest ({l_ts}). "
        f"{n_snapshots} total snapshots in DB."
    )
    return {"rows": rows, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 6: listing_count
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns a summary of how many listings are in the database: total, scored, "
        "unscored, and the date of the newest listing. Use when the question is about "
        "how many jobs were found, database size, or coverage. "
        "Do NOT use for scores, companies, gaps, or trends."
    ),
    params={},
)
def listing_count(config: Config) -> dict[str, Any]:
    path = _db(config)

    all_listings    = storage.get_listings(path, limit=10000, min_score=0)
    total_scored    = len(all_listings)
    total_unscored  = storage.count_unscored(path)
    total           = total_scored + total_unscored
    newest_fetch    = storage.last_fetch_time(path)

    rows = [{
        "total_listings":   total,
        "scored":           total_scored,
        "unscored":         total_unscored,
        "newest_fetch_at":  newest_fetch,
    }]
    summary = (
        f"{total} listings total: {total_scored} scored, "
        f"{total_unscored} unscored. Newest: {newest_fetch or 'none'}."
    )
    return {"rows": rows, "summary": summary}


# ---------------------------------------------------------------------------
# Tool 7: skill_demand
# ---------------------------------------------------------------------------

@tool(
    description=(
        "Returns how often one specific named skill appears in job listings — "
        "as a required skill vs nice-to-have, across all extractions in the database. "
        "Use when the question is about how in-demand one skill is, how often it appears, "
        "or whether it is required vs preferred. "
        "Requires a skill name. Do NOT use for gaps, scores, or trends."
    ),
    params={
        "skill": {
            "type": "string",
            "description": "The skill name to look up (e.g. 'python', 'tableau').",
            "default": "",
        }
    },
)
def skill_demand(config: Config, skill: str = "") -> dict[str, Any]:
    canon_skill = _safe_skill(skill, config.skill_aliases)
    if not canon_skill:
        return {"rows": [], "summary": "No skill specified."}

    extractions = storage.get_scored_listings_with_extractions(_db(config))

    required_count   = 0
    nice_count       = 0
    total_extractions = len(extractions)

    for e in extractions:
        facts    = e.get("extracted") or {}
        req_set  = {canonical(s, config.skill_aliases) for s in (facts.get("required_skills") or [])}
        nice_set = {canonical(s, config.skill_aliases) for s in (facts.get("nice_to_have") or [])}
        if canon_skill in req_set:
            required_count += 1
        elif canon_skill in nice_set:
            nice_count += 1

    total_appearances = required_count + nice_count
    if total_extractions > 0:
        req_pct  = round(required_count  / total_extractions * 100, 1)
        nice_pct = round(nice_count      / total_extractions * 100, 1)
    else:
        req_pct = nice_pct = 0.0

    rows = [{
        "skill":                 canon_skill,
        "required_in":           required_count,
        "nice_to_have_in":       nice_count,
        "total_appearances":     total_appearances,
        "required_pct":          req_pct,
        "nice_to_have_pct":      nice_pct,
        "total_extractions":     total_extractions,
    }]

    if total_appearances == 0:
        summary = (
            f"Skill '{canon_skill}' not found in any of {total_extractions} "
            f"extraction(s). It may not appear in your current listings."
        )
    else:
        summary = (
            f"'{canon_skill}' appears in {total_appearances}/{total_extractions} "
            f"extraction(s): {required_count} required ({req_pct}%), "
            f"{nice_count} nice-to-have ({nice_pct}%)."
        )
    return {"rows": rows, "summary": summary}
